name: Honu Lampworks
favicon: null
layout_spectrum: 0.33550319727510214
typography_spectrum: 0.6460981799755245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffe5'
    - '#0e2543'
    - '#3c5778'
    - '#bc7c31'
    - '#c8a76b'
  brandStrength: 0.1875
  lightness: 0.48715457902289927
  saturation: 0.6875
  rhythmicContrast: 0.6621876140125096
purpose: []
